### ISSUE TITLE
Enhance createbridge contract. Specs defined in attached doc. 

### ISSUE THREAD

**Issue by surabhil** [API-market/CreateBridge#1]
https://docs.google.com/document/d/1F5hkPGnInxpe53-NkEe2FRaiRnTB6kWUHRnbPJ1hTK4/edit?usp=sharing

**Comment by peteknowsai** [comment]
Issue moved to [API-market/ore-id #637](https://github.com/API-market/ore-id/issues/637) via [**ZenHub**](https://www.zenhub.com/)
